
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pdi_db
      MYSQL_USER: pdi_user
      MYSQL_PASSWORD: pdi_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: pdi_db
      MYSQL_USER: pdi_user
      MYSQL_PASSWORD: pdi_password
    deploy:
      resources:
        limits:
          memory: 512M  # Limita a memória para 512MB
          cpus: '1.0'   # Limita o uso da CPU para 1 núcleo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - web
    deploy:
      resources:
        limits:
          memory: 256M  # Limita a memória para 256MB
          cpus: '0.5'   # Limita o uso da CPU para 50% de um núcleo

volumes:
  mysql_data:
