# Generated by Django 3.2.25 on 2024-07-20 03:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='criado_em',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servico.servico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
