# Generated by Django 3.2.25 on 2024-07-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0005_auto_20240720_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='campo_extra',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
