# Generated by Django 3.2.25 on 2024-07-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0006_itemcarrinho_campo_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrinho',
            old_name='campo_extra',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servico.customuser'),
            preserve_default=False,
        ),
    ]
