# Generated by Django 3.2.25 on 2024-07-21 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0009_auto_20240721_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalhePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='carrinho',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='servico',
        ),
        migrations.DeleteModel(
            name='Profissional',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='ItemCarrinho',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.AddField(
            model_name='detalhepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='servico.pedido'),
        ),
        migrations.AddField(
            model_name='detalhepedido',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.servico'),
        ),
    ]
