# Generated by Django 3.2.25 on 2024-07-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0010_auto_20240721_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhepedido',
            name='desconto',
        ),
        migrations.AddField(
            model_name='detalhepedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
