# Generated by Django 3.2.25 on 2024-07-22 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0013_itemcarrinho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao_tecnica', models.CharField(max_length=255)),
                ('graduacao', models.CharField(max_length=255)),
                ('posgraduacao', models.CharField(max_length=255)),
                ('formacao_complementar', models.CharField(max_length=255)),
                ('cargo_desejado', models.CharField(max_length=255)),
                ('nucleo_de_trabalho', models.CharField(max_length=255)),
                ('data_admissao', models.DateField()),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('avaliado', models.BooleanField(default=False)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.pagamento')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
