# Generated by Django 3.2.25 on 2024-07-23 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0015_rename_compra_avaliacao_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='Pagamento',
            new_name='pagamento',
        ),
    ]
