# Generated by Django 3.2.25 on 2024-07-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0016_rename_pagamento_avaliacao_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('graduacao', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
    ]
