# Generated by Django 3.2.25 on 2024-07-24 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0019_auto_20240723_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhepedido',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='detalhepedido',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='detalhepedido',
            name='transacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='servico.transacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
