# Generated by Django 3.2.25 on 2024-08-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0024_transacao_valor_liquido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('idbloco', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id_tarefas', models.AutoField(primary_key=True, serialize=False)),
                ('tarefa', models.CharField(max_length=255)),
                ('prazo_registro', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('aprendizado', models.CharField(max_length=255)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='servico.bloco')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('idresultado', models.AutoField(primary_key=True, serialize=False)),
                ('data_resultado', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateField()),
                ('responsavel', models.CharField(max_length=255)),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='servico.avaliacao')),
            ],
        ),
        migrations.AddField(
            model_name='bloco',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='servico.resultado'),
        ),
    ]
